# Generated by Django 5.0.1 on 2026-01-27 21:19

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('role', models.CharField(blank=True, choices=[('wolf', 'Wolf'), ('citizen', 'Citizen'), ('seer', 'Agisienne (Seer)'), ('protector', 'Protector'), ('hunter', 'Sayad (Hunter)')], max_length=20, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('total_speaking_time', models.IntegerField(default=120)),
                ('speaking_time_used', models.IntegerField(default=0)),
                ('last_protected_player_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_room_code, max_length=6, unique=True)),
                ('admin_token', models.CharField(max_length=32, unique=True)),
                ('max_players', models.IntegerField(default=8)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_wolves', models.IntegerField(default=2)),
                ('num_seers', models.IntegerField(default=1)),
                ('num_protectors', models.IntegerField(default=1)),
                ('num_hunters', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('wolf_vote', 'Wolf Vote'), ('seer_inspect', 'Seer Inspect'), ('protector_protect', 'Protector Protect'), ('hunter_kill', 'Hunter Kill')], max_length=20)),
                ('night_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.player')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by', to='game.player')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room'),
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('setup', 'Setup'), ('night', 'Night'), ('day', 'Day'), ('leader_election', 'Leader Election'), ('voting', 'Voting'), ('finished', 'Finished')], default='setup', max_length=20)),
                ('night_number', models.IntegerField(default=0)),
                ('day_number', models.IntegerField(default=0)),
                ('timer_end', models.DateTimeField(blank=True, null=True)),
                ('current_speaker_id', models.IntegerField(blank=True, null=True)),
                ('speaking_order', models.JSONField(default=list)),
                ('wolves_voted', models.BooleanField(default=False)),
                ('seer_acted', models.BooleanField(default=False)),
                ('protector_acted', models.BooleanField(default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.room')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'nickname')},
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('leader', 'Leader Election'), ('elimination', 'Elimination Vote')], max_length=20)),
                ('vote_phase', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='game.player')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='game.player')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('player', 'vote_type', 'vote_phase')},
            },
        ),
    ]
